if exit code is not zero, abort and reset git tree

diff --git a/crawl-availability b/crawl-availability
--- a/crawl-availability
+++ b/crawl-availability
@@ -1,7 +1,16 @@
 #!/bin/bash
 
 cd "$(dirname "$0")"
+echo "started availability.js"
 node availability.js > /home/ec2-user/vaxxnzlocations.log 2>&1
+if [ $? -eq 0 ]; then
+    echo "index.js (locations job) completed successfully"
+else
+    echo "index.js (locations job) failed. skipping."
+    git fetch
+    git reset --hard origin/main
+    exit 1
+fi
 git add .
 git commit -m "updated from $(TZ='Pacific/Auckland' date)"
 git pull --rebase
diff --git a/crawl-healthpoint b/crawl-healthpoint
--- a/crawl-healthpoint
+++ b/crawl-healthpoint
@@ -1,7 +1,16 @@
 #!/bin/bash
 
 cd "$(dirname "$0")"
+echo "started healthpointLocationsOpenNow.ts"
 yarn ts-node healthpointLocationsOpenNow.ts > /home/ec2-user/vaxxnzlocationshealthpoint.log 2>&1
+if [ $? -eq 0 ]; then
+    echo "healthpointLocationsOpenNow.ts completed successfully"
+else
+    echo "healthpointLocationsOpenNow.ts failed. skipping."
+    git fetch
+    git reset --hard origin/main
+    exit 1
+fi
 git add .
 git commit -m "updated healthpoint from $(TZ='Pacific/Auckland' date)"
 git pull --rebase
diff --git a/crawl-locations b/crawl-locations
--- a/crawl-locations
+++ b/crawl-locations
@@ -1,9 +1,16 @@
 #!/bin/bash
 
 cd "$(dirname "$0")"
-echo "started index.js"
+echo "started index.js (locations job)"
 node index.js > /home/ec2-user/vaxxnzlocationslocations.log 2>&1
-echo "index.js finished"
+if [ $? -eq 0 ]; then
+    echo "index.js (locations job) completed successfully"
+else
+    echo "index.js (locations job) failed. skipping."
+    git fetch
+    git reset --hard origin/main
+    exit 1
+fi
 git add .
 git commit -m "updated locations from $(TZ='Pacific/Auckland' date)"
 git pull --rebase
